name: Coverage
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Prepare coverage data
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: >-
              -Zprofile
              -Ccodegen-units=1
              -Cinline-threshold=0
              -Clink-dead-code
              -Coverflow-checks=off
              -Zno-landing-pads
      - name: Aggregate coverage data
        uses: actions-rs/grcov@v0.1
      - name: Send results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
